FROM python:3.8

# Install Java
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk

# Install PySpark
RUN pip install pyspark

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container
COPY . .

# Run the PySpark script when the container launches
CMD ["spark-submit", "my_script.py"]
